### ISSUE TITLE
[Feature request]: sbb-button  grey variant

### ISSUE THREAD

**Issue by sebastiencloss** [lyne-design-system/lyne-components#1385] opened 2022-09-21 13:48 UTC
### Request type

Request for enhancement of a component

### Functionality

grey variant doesn't exist yet (only red/white/translucent)

### Is there a design proposal?

Yes

### Link to design proposal file (optional)

https://www.figma.com/file/54pM6C0HgMYvGThnPVG7JB/04%3A-Design-%E2%80%93-WCMS?node-id=506%3A366336

### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/lyne-design-system/lyne-components/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/lyne-design-system/lyne-components/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Comment by kyubisation** [comment] 2022-09-21 14:00
Duplicate of #1131 
Currently being worked on in #1328 by @HendrikExtSBB. No timeline available yet.

**Closed by kyubisation** 2022-09-21 14:00 UTC
Labels: type: enhancement 💡

**Comment by jeripeierSBB** [comment] 2022-09-22 05:53
@sebastiencloss All available button versions are already implemented. What do you mean exactly with grey variant? there is no such variant. If you mean the one on the screenshot, it's the translucent variant (you can see it in the right column).
<img width="1275" alt="Bildschirmfoto 2022-09-22 um 07 52 24" src="https://user-images.githubusercontent.com/29278232/191668618-7a45b5bf-4d43-43fa-b464-6d4f9743932d.png">
